# Vetores e Álgebra Matricial

In [1]:
import numpy as np

### Vetores (coluna)

In [2]:
a = np.array([[1], [2], [5]])
a

array([[1],
       [2],
       [5]])

In [3]:
b = np.array([[3], [5], [3]])
b

array([[3],
       [5],
       [3]])

### Soma de dois vetores

In [4]:
a + b

array([[4],
       [7],
       [8]])

### Produto interno

In [8]:
c = np.dot(np.transpose(b), a)
c

array([[28]])

In [9]:
c = np.transpose(b).dot(a)
c

array([[28]])

In [10]:
c = b.T.dot(a)
c

array([[28]])

### Matrizes

In [12]:
A = np.array([[7,5,3],[5,6,2],[2,2,8]])
A

array([[7, 5, 3],
       [5, 6, 2],
       [2, 2, 8]])

In [13]:
B = np.array([[6,3,3],[12,6,6],[4,5,8]])
B

array([[ 6,  3,  3],
       [12,  6,  6],
       [ 4,  5,  8]])

### Multiplicação por escalar

In [16]:
W = 2
W*A

array([[14, 10,  6],
       [10, 12,  4],
       [ 4,  4, 16]])

### Produto de duas matrizes (não é comutativo)

In [17]:
A.dot(B)

array([[114,  66,  75],
       [110,  61,  67],
       [ 68,  58,  82]])

In [18]:
B.dot(A)

array([[ 63,  54,  48],
       [126, 108,  96],
       [ 69,  66,  86]])

### Propriedade

(A B)^T = B^T A^T

In [19]:
np.transpose(A.dot(B))

array([[114, 110,  68],
       [ 66,  61,  58],
       [ 75,  67,  82]])

In [20]:
np.transpose(B).dot(np.transpose(A))

array([[114, 110,  68],
       [ 66,  61,  58],
       [ 75,  67,  82]])

### Determinante de uma matriz

In [21]:
np.linalg.det(A)

122.00000000000003

In [22]:
np.linalg.det(B)

0.0

### Traço de uma matriz

In [23]:
np.trace(A)

21

In [24]:
np.trace(B)

20

### Posto de uma matriz

In [25]:
np.linalg.matrix_rank(A)

3

In [26]:
np.linalg.matrix_rank(B)

2

### Dimensões de uma matriz

In [27]:
A.shape

(3, 3)

In [34]:
a.shape

(3, 1)

### Matriz identidade

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(3).dot(A)

array([[7., 5., 3.],
       [5., 6., 2.],
       [2., 2., 8.]])

### Matriz inversa

In [31]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.36065574, -0.27868852, -0.06557377],
       [-0.29508197,  0.40983607,  0.00819672],
       [-0.01639344, -0.03278689,  0.13934426]])

In [32]:
# Conferindo

np.round(A.dot(A_inv), 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

In [33]:
np.round(A_inv.dot(A), 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

### Autovalores e autovetores

In [35]:
np.linalg.eig(A)

EigResult(eigenvalues=array([13.3914202 ,  1.48862351,  6.11995629]), eigenvectors=array([[-0.67062299, -0.66402049, -0.34287821],
       [-0.57909059,  0.74727695, -0.43819835],
       [-0.46359346, -0.02557262,  0.83091319]]))

In [36]:
lam = np.linalg.eig(A)[0]
lam

array([13.3914202 ,  1.48862351,  6.11995629])

In [37]:
e = np.linalg.eigh(A)[1]
e

array([[-0.66566978, -0.37640085, -0.64436491],
       [ 0.74584214, -0.30715729, -0.5910786 ],
       [-0.02456111,  0.87405766, -0.48520094]])

In [38]:
e[:,0]

array([-0.66566978,  0.74584214, -0.02456111])

In [39]:
np.transpose(e[:,0]).dot(e[:,0])

1.0000000000000002

In [41]:
np.transpose(e[:,0]).dot(e[:,1])

-1.214306433183765e-16

In [42]:
# Matriz de autovetores ortogonal

P = np.transpose(e).dot(e)

In [51]:
np.round(np.linalg.inv(P), 2)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
np.round(np.transpose(P), 2)

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0., -0.,  1.]])

In [45]:
np.linalg.det(P)

1.0000000000000004

### Decomposição de Cholesky

In [46]:
A

array([[7, 5, 3],
       [5, 6, 2],
       [2, 2, 8]])

In [49]:
W = np.linalg.cholesky(A)
W

array([[2.64575131, 0.        , 0.        ],
       [1.88982237, 1.55838744, 0.        ],
       [0.75592895, 0.3666794 , 2.70076242]])

In [48]:
W.dot(W.T)

array([[7., 5., 2.],
       [5., 6., 2.],
       [2., 2., 8.]])

### Produto de Kronecker

In [50]:
np.kron(np.eye(4), A)

array([[7., 5., 3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 6., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [2., 2., 8., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 7., 5., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 6., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 2., 8., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 7., 5., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 5., 6., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 2., 8., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 7., 5., 3.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 5., 6., 2.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 2., 8.]])